const sampleListings = [
  {
    title: "Luxurious Penthouse Suite",
    description: "Stunning city views from this top-floor luxury apartment.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 3500,
    location: "Manhattan",
    country: "USA",
  },
  {
    title: "Beachfront Villa Paradise",
    description: "Private beach access with this extravagant seaside villa.",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    price: 4200,
    location: "Maldives",
    country: "Maldives",
  },
  {
    title: "Mountain Retreat Chalet",
    description: "Ski-in/ski-out chalet with panoramic mountain views.",
    image: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb",
    price: 2800,
    location: "Aspen",
    country: "USA",
  },
  {
    title: "Tuscan Vineyard Estate",
    description: "Historic villa surrounded by rolling hills and vineyards.",
    image: "https://images.unsplash.com/photo-1523531294919-4bcd7c65e216",
    price: 5000,
    location: "Florence",
    country: "Italy",
  },
  {
    title: "Tropical Island Bungalow",
    description: "Overwater bungalow in a crystal-clear lagoon.",
    image: "https://images.unsplash.com/photo-1439066615861-d1af74d74000",
    price: 3800,
    location: "Bora Bora",
    country: "French Polynesia",
  },
  {
    title: "Arctic Glass Igloo",
    description:
      "Watch the Northern Lights from your bed in this unique igloo.",
    image: "https://images.unsplash.com/photo-1517823382935-51bfcb0ec6bc",
    price: 2200,
    location: "Rovaniemi",
    country: "Finland",
  },
  {
    title: "Safari Lodge Experience",
    description: "Luxury tent with up-close wildlife viewing opportunities.",
    image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e",
    price: 3200,
    location: "Serengeti",
    country: "Tanzania",
  },
  {
    title: "Historic Castle Stay",
    description: "Live like royalty in this restored medieval castle.",
    image: "https://images.unsplash.com/photo-1533154683836-84ea7a0bc310",
    price: 4500,
    location: "Edinburgh",
    country: "Scotland",
  },
  {
    title: "Cliffside Mediterranean Villa",
    description: "Dramatic sea views from this cliffside retreat.",
    image: "https://images.unsplash.com/photo-1515859005217-8a1f08870f59",
    price: 3900,
    location: "Santorini",
    country: "Greece",
  },
  {
    title: "Rainforest Eco-Lodge",
    description: "Sustainable luxury in the heart of the Amazon rainforest.",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    price: 2600,
    location: "Manaus",
    country: "Brazil",
  },
  {
    title: "Dubai Skyline Apartment",
    description: "Ultra-modern apartment with views of the Burj Khalifa.",
    image: "https://images.unsplash.com/photo-1518684079-3c830dcef090",
    price: 3300,
    location: "Dubai",
    country: "UAE",
  },
  {
    title: "Parisian Haussmann Flat",
    description: "Elegant apartment in a classic Haussmann building.",
    image: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3",
    price: 2900,
    location: "Paris",
    country: "France",
  },
  {
    title: "Bali Rice Terrace Villa",
    description: "Serene villa overlooking lush rice terraces.",
    image: "https://images.unsplash.com/photo-1537953773345-d172ccf13cf1",
    price: 2400,
    location: "Ubud",
    country: "Indonesia",
  },
  {
    title: "Alaskan Wilderness Cabin",
    description: "Remote log cabin with stunning glacier views.",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b",
    price: 2100,
    location: "Anchorage",
    country: "USA",
  },
  {
    title: "Tokyo Tower View Suite",
    description: "Sleek suite with iconic views of Tokyo Tower.",
    image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26",
    price: 3100,
    location: "Tokyo",
    country: "Japan",
  },
  {
    title: "Moroccan Riad Experience",
    description: "Traditional riad with intricate tilework and courtyard.",
    image: "https://images.unsplash.com/photo-1512753360435-329c4535a9a7",
    price: 2300,
    location: "Marrakech",
    country: "Morocco",
  },
  {
    title: "New Zealand Lakeside Retreat",
    description: "Modern home with breathtaking views of Lake Wakatipu.",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9",
    price: 3600,
    location: "Queenstown",
    country: "New Zealand",
  },
  {
    title: "Caribbean Private Island",
    description: "Entire island for your exclusive use in the Caribbean.",
    image: "https://images.unsplash.com/photo-1545579133-99bb5ab189bd",
    price: 10000,
    location: "British Virgin Islands",
    country: "British Virgin Islands",
  },
  {
    title: "Swiss Alpine Luxury Chalet",
    description: "High-end chalet with private spa and mountain views.",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4",
    price: 4800,
    location: "Zermatt",
    country: "Switzerland",
  },
  {
    title: "Balinese Beachfront Resort",
    description: "Expansive resort property with private beach access.",
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6",
    price: 3700,
    location: "Seminyak",
    country: "Indonesia",
  },
  {
    title: "Icelandic Geothermal Retreat",
    description: "Modern home with private geothermal hot spring.",
    image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1",
    price: 2700,
    location: "Reykjavik",
    country: "Iceland",
  },
  {
    title: "Australian Outback Station",
    description: "Authentic outback experience on a working cattle station.",
    image: "https://images.unsplash.com/photo-1529108190281-9a4f620bc2d8",
    price: 2500,
    location: "Alice Springs",
    country: "Australia",
  },
  {
    title: "Lake Como Villa",
    description: "Historic villa with lakeside gardens and boat dock.",
    image: "https://images.unsplash.com/photo-1518735869015-566a18eae4be",
    price: 5500,
    location: "Como",
    country: "Italy",
  },
  {
    title: "Kyoto Zen Garden Ryokan",
    description: "Traditional ryokan with serene zen gardens.",
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186",
    price: 2000,
    location: "Kyoto",
    country: "Japan",
  },
  {
    title: "Peruvian Andes Lodge",
    description: "Mountain lodge with views of Machu Picchu.",
    image: "https://images.unsplash.com/photo-1526392060635-9d6019884377",
    price: 2400,
    location: "Cusco",
    country: "Peru",
  },
  {
    title: "Croatian Coastal Villa",
    description: "Seaside villa with infinity pool overlooking the Adriatic.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
    price: 3400,
    location: "Dubrovnik",
    country: "Croatia",
  },
  {
    title: "African Treehouse Lodge",
    description: "Luxury treehouse in the heart of a wildlife reserve.",
    image: "https://images.unsplash.com/photo-1544984243-ec57ea16fe25",
    price: 2900,
    location: "Kruger National Park",
    country: "South Africa",
  },
  {
    title: "Portuguese Wine Estate",
    description: "Historic quinta in the Douro Valley wine region.",
    image: "https://images.unsplash.com/photo-1592285896110-8d88b5b3a5d8",
    price: 3800,
    location: "Porto",
    country: "Portugal",
  },

  {
    title: "Cambodian ",
    description: "Luxurious resort near ancient Angkor temples.",
    image: "https://images.unsplash.com/photo-1528181304800-259b08848526",
    price: 2200,
    location: "Siem Reap",
    country: "Cambodia",
  },
];
module.exports = sampleListings;
